version: '{build}'

image: Visual Studio 2017
environment:
  matrix:
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      BUILD_SHARED: 'OFF'


build_script:
- cmd: >-
    echo "%cd%"
    
    cd ..
    
    git clone -b develop https://github.com/butterflyy/externals.git  --single-branch --depth=1
    
    cd externals


    echo "Build glog"

    cd glog-0.4.0
    
    mkdir build

    cd build

    cmake -G %GENERATOR%
    
    cmake --build .
    
    cd ../..


    echo "Build gtest"
    
    cd googletest-release-1.10.0
    
    mkdir build
    
    cd build
    
    cmake .. -G %GENERATOR% -Dgtest_force_shared_crt=ON -DBUILD_GMOCK=OFF -DINSTALL_GTEST=OFF
    
    cmake --build .


    echo "Build simple socket"
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    mkdir build
    
    cd build
    
    cmake .. -G %GENERATOR% -DEXTERNALS_DIR=C:/projects/externals
    
    cmake --build .
  
test_script:
  - C:\projects\simple-socket\build\Bin\Debug\UnitTest.exe
