version: '{build}'

image: Visual Studio 2017
environment:
  matrix:
    - GENERATOR: '"Visual Studio 15 2017 Win64"'
      BUILD_TYPE: Release
      WCHAR: 'OFF'
      BUILD_SHARED: 'OFF'


build_script:
- cmd: >-
    echo "%cd%"
    
    cd ..
    
    git clone -b develop https://github.com/butterflyy/externals.git  --single-branch --depth=1
    
    cd externals


    echo "Build glog"
    
    git clone -b v0.4.0 https://github.com/google/glog.git --single-branch --depth=1
    
    cd glog
    
    cmake G %GENERATOR%
    
    cmake --build .
    
    cd ..
    
    rename glog glog-0.4.0


    echo "Build gtest"
    
    git clone -b release-1.10.0 https://github.com/google/googletest.git  --single-branch --depth=1
    
    cd googletest
    
    mkdir build
    
    cd build
    
    cmake .. G %GENERATOR% -Dgtest_force_shared_crt=ON
    
    cmake --build .
    
    cd ../..
    
    rename googletest googletest-release-1.10.0


    echo "Build simple socket"
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    mkdir build
    
    cd build
    
    cmake .. G %GENERATOR% -DGLOG_INCLUDE_DIR=../externals
    
    cmake --build .


before_test:
#  - set PATH=%PATH%;C:\projects\spdlog\build\%BUILD_TYPE%
  
test_script:
#  - C:\projects\spdlog\build\tests\%BUILD_TYPE%\spdlog-utests.exe
