version: '{build}'

image:
  - Visual Studio 2017
  
environment:
  GYP_MSVS_VERSION: 2017

platform:
  - Win32

configuration:
  - Debug
  - Release


build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor.bat

test_script:
#  - src\client\windows\%CONFIGURATION%\client_tests.exe
#  - src\tools\windows\%CONFIGURATION%\dump_syms_unittest.exe
#  - build\out\Debug\Win32\%CONFIGURATION%\

artifacts:
  - path: '**\*.exe'
#  - path: '**\*.lib'
