version: 1.0.{build}
image:
  - Visual Studio 2013
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
clone_depth: 1
build:
  parallel: true

environment:
  matrix:
    only:
      - image: Visual Studio 2013
  build:
    project: msvc\libusb_2013.sln
