version: '{build}'

image:
  - Visual Studio 2013
  
environment:
  GYP_MSVS_VERSION: 2013

platform:
  - Win32

configuration:
  - Debug
  - Release


build_script:
  - echo "%cd%"
  - cd ..
  - git clone -b develop https://github.com/butterflyy/externals.git  --single-branch --depth=1
  - cd %APPVEYOR_BUILD_FOLDER%
  - msbuild api/simple_client_socket/simple_client_socket.vcxproj
  - msbuild api/simple_server_socket/simple_server_socket.vcxproj

test_script:
#  - src\client\windows\%CONFIGURATION%\client_tests.exe
#  - src\tools\windows\%CONFIGURATION%\dump_syms_unittest.exe
#  - build\out\Debug\Win32\%CONFIGURATION%\

artifacts:
  - path: '**\*.exe'
#  - path: '**\*.lib'
